CREATE TABLE Users
(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(50) NOT NULL UNIQUE,
    password varchar(100) NOT NULL,
    email varchar(50) NOT NULL UNIQUE,
    role varchar(30) NOT NULL
);

ALTER TABLE Users
ADD COLUMN isEnabled BOOLEAN DEFAULT FALSE;

CREATE TABLE ConfirmationToken(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    confirmation_token VARCHAR DEFAULT NULL UNIQUE,
    date timestamp with time zone NOT NULL,
    user_id int REFERENCES Users(id) ON DELETE CASCADE
);

ALTER TABLE ConfirmationToken
RENAME COLUMN date TO createdDate;

CREATE TABLE Product(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title varchar(50) NOT NULL UNIQUE,
    img_name varchar(50),
    date timestamp with time zone NOT NULL,
    price int,
    category varchar(30) NOT NULL
);

ALTER TABLE Product
    ADD amount int CHECK (amount >= 0) DEFAULT 0;

ALTER TABLE Product
    ADD rating NUMERIC(5, 2) CHECK ( rating >= 0.00) DEFAULT 0.00;

CREATE TABLE Orders
(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id int REFERENCES Users(id) ON DELETE CASCADE,
    order_num int NOT NULL UNIQUE,
    creation_time timestamp with time zone NOT NULL,
    total_sum int NOT NULL
);

CREATE TABLE Order_details(
        id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        product_id int REFERENCES Product(id) ON DELETE NO ACTION,
        order_id int REFERENCES Orders(id),
        quantity int,
        price int NOT NULL,
        total_sum int
);

ALTER TABLE Order_details
DROP CONSTRAINT order_details_order_id_fkey;

ALTER TABLE Order_details
ADD CONSTRAINT order_details_order_id_fkey
FOREIGN KEY (order_id)
REFERENCES Orders(id)
ON DELETE CASCADE;

CREATE TABLE Bucket(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id int REFERENCES Users (id) ON DELETE CASCADE UNIQUE
);

CREATE TABLE Bucket_Product(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    bucket_id int REFERENCES Bucket(id) ON DELETE CASCADE,
    product_id int REFERENCES Product(id) ON DELETE CASCADE
);

ALTER TABLE order_details
    DROP CONSTRAINT order_details_product_id_fkey;

ALTER TABLE order_details
    ADD CONSTRAINT order_details_product_id_fkey
    FOREIGN KEY (product_id)
    REFERENCES product(id)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;






